import { Router } from "express";
import authController from "./auth/auth-controller";
import projectController from "./projects/project-controller";
import userController from "./user/user-controller";
import inviteController from "./invites/invite-controller";
import taskController from "./tasks/task-controller";
import multer from "multer";
import backlogController from "./backlog/backlog-controller";
import sprintController from "./sprints/sprint-controller";
import analyticsController from "./analytics/analytics-controller";
import sprintService from "./sprints/sprint-service";
import projectService from "./projects/project-service";
import phaseController from "./phase/phase-controller";
import requirementService from "./requirements/requirement-service";
import requirementController from "./requirements/requirement-controller";

const router = Router();

const upload = multer();

router.post("/project", projectController.newProject);
router.get("/user-projects", projectController.getUserProjects);
router.get("/project/:id", projectController.getProjectById);
router.get("/users", userController.fetchUsers);
router.post("/invite", inviteController.createInvite);
router.get("/invited/:projectId", inviteController.getInvited);
router.get("/user/:userId", userController.getUserById);
router.get("/invites-to-user", inviteController.getInvitesToUser);
router.post("/see-invite/:inviteId", inviteController.seeInvite);
router.delete("/leave-project/:projectId", projectController.leaveProject);
router.post("/delete-participant/:projectId", projectController.deleteParticipant);
router.post("/cancel-invite", inviteController.cancelInvite);
router.get(`/project-tasks/:projectId`, taskController.getProjectTasks);
router.post(`/task`, taskController.addTask);
router.post(`/user-update/:userId`, userController.updateUser);
router.post("/avatar", upload.single("file"), userController.setAvatar);
router.patch("/task-check/:taskId", taskController.checkTask);
router.patch("/task-uncheck/:taskId", taskController.unCheckTask);
router.get("/backlogs/:projectId", backlogController.getProjectBacklogs);
router.post("/backlog/:projectId", backlogController.createBacklog);
router.post("/sprint", sprintController.createSprint);
router.get("/sprints/:backlogId", sprintController.getBacklogSprints);
router.get("/backlog-tasks/:backlogId", backlogController.getBacklogTasks);
router.get("/sprint-tasks/:sprintId", sprintController.getSprintTasks);
router.post("/sprint-task", sprintController.pushTask);
router.post("/sprint-pull-task", sprintController.pullTaskIntoBacklog);
router.patch("/status/:taskId", taskController.setStatus);
router.patch("/assign", taskController.assignTask);
router.get("/participants/:projectId", projectController.getParticipants);
router.get("/user-rights/:projectId", projectController.getUserRights);
router.post("/analytics/task-amount", analyticsController.taskAmount);
router.get("/sprint/:sprintId", sprintController.getSprintById);
router.put("/sprint/:sprintId", sprintController.editSprint);
router.post("/analytics/task-ratio", analyticsController.taskRatio);
router.post("/analytics/created-task-amount", analyticsController.createdTaskAmount);
router.post("/analytics/predict-ratio", analyticsController.predictRatio);
router.get("/rights/:projectId", projectController.getRights);
router.patch("/rights/:projectId", projectController.setRights);
router.delete("/task/:taskId", taskController.deleteTask);
router.post("/owner/:projectId", projectController.changeOwner);
router.get("/task/:taskId", taskController.getTaskById);
router.put("/task/:taskId", taskController.updateTask);
router.get("/owner/:projectId", projectController.getOwnerId);
router.delete("/sprint/:sprintId", sprintController.deleteSprint);
router.delete("/project/:projectId", projectController.deleteProject);
router.post("/new-phase", phaseController.createPhase);
router.post("/phases/:projectId", phaseController.getProjectPhases);
router.get("/phase-tasks/:phaseId", taskController.getPhaseTasks);
router.delete("/phase/:phaseId", phaseController.deletePhase);
router.get("/active-index/:projectId", phaseController.getActiceWaterfallIndex);
router.get("/move-up/:phaseId", phaseController.moveUp);
router.get("/move-down/:phaseId", phaseController.moveDown);
router.get("/price/:projectId", projectController.calculatePrice);
router.patch("/phase-charge/:phaseId", phaseController.assignCharge);
router.post("/sub-task", taskController.createSubTask);
router.get("/check-sub-task/:subTaskId", taskController.checkSubTask);
router.get("/sub-tasks/:parentTaskId", taskController.getSubTasks);
router.get("/subtasks-done/:taskId", taskController.allSubTasksAreDone);
router.delete("/sub-task/:subTaskId", taskController.deleteSubTask);
router.put("/project/:projectId", projectController.editProject);
router.get("/done-stats/:userId", authController.getDoneStatistics);
router.get("/login-stats/:userId", authController.getLoginStatistics);
router.get("/requirements/:projectId", requirementController.getRequirements);

export default router;